export const mockData = [
  {
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Alligator_snapping_turtle.jpg',
    name: 'Alligator Snapping Turtle',
    latin: 'Macroclemys temmnicki',
    lifespan: '70',
    habitat: 'Fresh water lakes and rivers',
  },
  {
    name: 'Snow Leopard',
    latin: 'Uncia uncia',
    img: 'https://upload.wikimedia.org/wikipedia/commons/e/e2/Apeldoorn_Apenheul_zoo_Bonobo.jpg',
    lifespan: '14',
    habitat:
      'Mountain regions, including grassland, scrubland, and open woodland',
  },
  // {
  //   name: 'Bonobo',
  //   latin_name: 'Pan paniscus',
  //   animal_type: 'Mammal',
  //   active_time: 'Diurnal',
  //   length_min: '2.3',
  //   length_max: '2.8',
  //   weight_min: '68',
  //   weight_max: '86',
  //   lifespan: '31',
  //   habitat: 'Tropical forest',
  //   diet: 'Fruit, seeds, leaves, flowers, fungi, eggs, and small animals',
  //   geo_range: 'Democratic Republic of the Congo',
  //   img:
  //     'https://upload.wikimedia.org/wikipedia/commons/e/e2/Apeldoorn_Apenheul_zoo_Bonobo.jpg',
  //   id: 44,
  // },
  // {
  //   name: 'Alligator Gar',
  //   latin_name: 'Lepisosteus spatula',
  //   animal_type: 'Fish',
  //   active_time: 'Nocturnal',
  //   length_min: '8',
  //   length_max: '10',
  //   weight_min: '250',
  //   weight_max: '300',
  //   lifespan: '50',
  //   habitat: 'Rivers, lakes and other bodies of fresh and brackish water',
  //   diet: 'Fish and other small animals',
  //   geo_range: 'North America',
  //   img:
  //     'https://upload.wikimedia.org/wikipedia/commons/1/16/Alligator_Gar_10.JPG',
  //   id: 7,
  // },
  // {
  //   name: 'Bat-eared Fox',
  //   latin_name: 'Otocyon megalotis',
  //   animal_type: 'Mammal',
  //   active_time: 'Nocturnal',
  //   length_min: '1.5',
  //   length_max: '2.2',
  //   weight_min: '7',
  //   weight_max: '12',
  //   lifespan: '13',
  //   habitat: 'Savannah',
  //   diet: 'Primarily termites, beetles, and other insects',
  //   geo_range: 'Eastern and Southern Africa',
  //   img:
  //     'https://upload.wikimedia.org/wikipedia/commons/8/84/Otocyon_megalotis_-_Etosha_2014.jpg',
  //   id: 27,
  // },
  // {
  //   name: 'Southern Brazilian Ocelot',
  //   latin_name: 'Leopardus pardalis mitis',
  //   animal_type: 'Mammal',
  //   active_time: 'Nocturnal',
  //   length_min: '2.4',
  //   length_max: '2.8',
  //   weight_min: '20',
  //   weight_max: '34',
  //   lifespan: '20',
  //   habitat: 'Tropical and subtropical forest',
  //   diet: 'Small mammals such as rodents, possums and armadillos, some reptiles and birds',
  //   geo_range: 'Central and eastern South America',
  //   img:
  //     'https://upload.wikimedia.org/wikipedia/commons/f/f8/Ocelot_%28Jaguatirica%29_Zoo_Itatiba.jpg',
  //   id: 165,
  // },
  // {
  //   name: 'Lappet-faced Vulture',
  //   latin_name: 'Torgos tracheliotos',
  //   animal_type: 'Bird',
  //   active_time: 'Diurnal',
  //   length_min: '2.6',
  //   length_max: '3.8',
  //   weight_min: '9.7',
  //   weight_max: '18.7',
  //   lifespan: '50',
  //   habitat: 'Savannah, semi-desert and desert',
  //   diet: 'Carrion, small mammals and birds',
  //   geo_range: 'Africa and Middle East',
  //   img:
  //     'https://upload.wikimedia.org/wikipedia/commons/b/b4/2012-lappet-faced-vulture.jpg',
  //   id: 102,
  // },
  // {
  //   name: 'Visayan Warty Pig',
  //   latin_name: 'Sus cebifrons',
  //   animal_type: 'Mammal',
  //   active_time: 'Nocturnal',
  //   length_min: '3',
  //   length_max: '4',
  //   weight_min: '55',
  //   weight_max: '90',
  //   lifespan: '15',
  //   habitat: 'Rainforest',
  //   diet: 'Fruits, roots and crops',
  //   geo_range: 'Philippines',
  //   img:
  //     'https://upload.wikimedia.org/wikipedia/commons/8/89/VisayanWartyPig01.jpg',
  //   id: 183,
  // },
  // {
  //   name: 'Mini-Juliana Pig',
  //   latin_name: 'Sus domesticus',
  //   animal_type: 'Mammal',
  //   active_time: 'Diurnal',
  //   length_min: '2',
  //   length_max: '2.2',
  //   weight_min: '35',
  //   weight_max: '55',
  //   lifespan: '18',
  //   habitat: 'Domestic habitat',
  //   diet: 'Pellets, fruits and veggies',
  //   geo_range: 'Raised domestically around the world',
  //   img:
  //     'https://americanminipigassociation.com/wp-content/uploads/2015/03/image-3-e1426360082120.jpeg',
  //   id: 119,
  // },
  // {
  //   name: 'Quince Monitor',
  //   latin_name: 'Varanus melinus',
  //   animal_type: 'Reptile',
  //   active_time: 'Diurnal',
  //   length_min: '4',
  //   length_max: '5',
  //   weight_min: '28',
  //   weight_max: '32',
  //   lifespan: '10',
  //   habitat: 'Tropical forest and swamp',
  //   diet: 'Small animals, such as insects and frogs, and eggs',
  //   geo_range: 'Sula Islands, Indonesia.',
  //   img:
  //     'https://zooinstitutes.com/img/animals/86/861567355186_45.jpg',
  //   id: 140,
  // },
];
